# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': '回答表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': '选项表'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '问题表'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name_plural': '问卷表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '员工表'},
        ),
        migrations.AlterField(
            model_name='question',
            name='caption',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tp',
            field=models.IntegerField(choices=[(1, '打分'), (2, '单选'), (3, '评价')], verbose_name='回答方式'),
        ),
    ]
