# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171209_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='title',
            field=models.CharField(max_length=32, verbose_name='班级名'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=32, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='option',
            name='qs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.IntegerField(verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Userinfo', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
